// Mock данные для VIP-клиентов (A-Club)

export const mockVipClients = [
  {
    id: 'VIP001',
    name: 'Иванов Иван Иванович',
    photo: 'https://via.placeholder.com/80',
    status: 'Platinum',
    predictedLiquidity: 2500000,
    aum: 45000000,
    riskProfile: 'Агрессивный',
    lastContact: '2024-01-15',
    notes: 'Интересуется акциями технологических компаний',
  },
  {
    id: 'VIP002',
    name: 'Петрова Анна Сергеевна',
    photo: 'https://via.placeholder.com/80',
    status: 'Gold',
    predictedLiquidity: 1800000,
    aum: 32000000,
    riskProfile: 'Консервативный',
    lastContact: '2024-01-14',
    notes: 'Предпочитает облигации и депозиты',
  },
  {
    id: 'VIP003',
    name: 'Сидоров Петр Александрович',
    photo: 'https://via.placeholder.com/80',
    status: 'Platinum',
    predictedLiquidity: 3200000,
    aum: 68000000,
    riskProfile: 'Агрессивный',
    lastContact: '2024-01-13',
    notes: 'Активный трейдер, нужны рекомендации по акциям',
  },
  {
    id: 'VIP004',
    name: 'Козлова Мария Дмитриевна',
    photo: 'https://via.placeholder.com/80',
    status: 'Gold',
    predictedLiquidity: 950000,
    aum: 18000000,
    riskProfile: 'Умеренный',
    lastContact: '2024-01-12',
    notes: 'Рассматривает диверсификацию портфеля',
  },
  {
    id: 'VIP005',
    name: 'Смирнов Алексей Викторович',
    photo: 'https://via.placeholder.com/80',
    status: 'Platinum',
    predictedLiquidity: 4200000,
    aum: 95000000,
    riskProfile: 'Агрессивный',
    lastContact: '2024-01-11',
    notes: 'Высокая ликвидность, готов к крупным инвестициям',
  },
  {
    id: 'VIP006',
    name: 'Волкова Елена Игоревна',
    photo: 'https://via.placeholder.com/80',
    status: 'Gold',
    predictedLiquidity: 1200000,
    aum: 25000000,
    riskProfile: 'Консервативный',
    lastContact: '2024-01-10',
    notes: 'Интересуется защитными активами',
  },
  {
    id: 'VIP007',
    name: 'Новиков Дмитрий Сергеевич',
    photo: 'https://via.placeholder.com/80',
    status: 'Platinum',
    predictedLiquidity: 2800000,
    aum: 52000000,
    riskProfile: 'Умеренный',
    lastContact: '2024-01-09',
    notes: 'Планирует ребалансировку портфеля',
  },
  {
    id: 'VIP008',
    name: 'Морозова Ольга Владимировна',
    photo: 'https://via.placeholder.com/80',
    status: 'Gold',
    predictedLiquidity: 750000,
    aum: 15000000,
    riskProfile: 'Консервативный',
    lastContact: '2024-01-08',
    notes: 'Новый клиент, требуется консультация',
  },
];

export const mockMarketData = [
  {
    id: 'SBER',
    name: 'Сбербанк',
    type: 'Акции',
    category: 'Growth',
    currentPrice: 285.50,
    changePercent: 5.2,
    changeDirection: 'up',
    risk: 'high',
    minInvestment: 100000,
    description: 'Лидер банковского сектора, стабильный рост',
    logo: 'https://via.placeholder.com/40?text=SBER',
  },
  {
    id: 'LKOH',
    name: 'Лукойл',
    type: 'Акции',
    category: 'Growth',
    currentPrice: 7420.00,
    changePercent: 3.8,
    changeDirection: 'up',
    risk: 'high',
    minInvestment: 150000,
    description: 'Крупнейшая нефтяная компания России',
    logo: 'https://via.placeholder.com/40?text=LKOH',
  },
  {
    id: 'OFZ26207',
    name: 'ОФЗ 26207',
    type: 'Облигации',
    category: 'Safe',
    currentPrice: 98.5,
    changePercent: 0.2,
    changeDirection: 'up',
    risk: 'low',
    yield: 14.2,
    minInvestment: 50000,
    description: 'Государственные облигации, доходность к погашению 14.2%',
    logo: 'https://via.placeholder.com/40?text=OFZ',
  },
  {
    id: 'TINKOFF',
    name: 'Тинькофф Вечный портфель',
    type: 'Фонд',
    category: 'Diversified',
    currentPrice: 1250.00,
    changePercent: 2.1,
    changeDirection: 'up',
    risk: 'medium',
    minInvestment: 10000,
    description: 'Диверсифицированный фонд с умеренным риском',
    logo: 'https://via.placeholder.com/40?text=TINK',
  },
  {
    id: 'GLDRUB',
    name: 'Золото',
    type: 'Валюта/Металл',
    category: 'Safe',
    currentPrice: 6250.00,
    changePercent: 1.5,
    changeDirection: 'up',
    risk: 'low',
    minInvestment: 50000,
    description: 'Защитный актив, хедж от инфляции',
    logo: 'https://via.placeholder.com/40?text=GOLD',
  },
];

